# <center> **Weather Report Forecasting Analysis** </center>
## <center> **Module 1: Pre-processing, Analysing Data using Python** </center>

***
## Introduction :

Weather prediction helps to determine future climate changes. It has a great impact on various aspects of human life. Weather forecasting is done by collecting data on the current state of the atmosphere and applying a scientific understanding of atmospheric processes to predict and analyse atmospheric progression. In the project, we have been provided with day wise weather data from Jan 2022 to July 2033 which is a predicted
data. 

![download.gif](https://cdn.dribbble.com/users/1046127/screenshots/3987643/media/f8536f8486d6a831bc8ceff562e6e6e6.gif)


### Objectives of Module 1 :

• Handling null values, deletion or transformation of irrelevant values.

• Datatype transformation, formatting, removing duplicates.

• To Correct the years for given data set

• Encoding data into suitable format i.e. UTF8

• To get a cleaned dataset csv file


### Variables present in the dataset :

Columns i.e. attributes present in the dataset are as follows :


• Date- Date for which predicted data is given

• Average temperature (°F) - Avg. temperature at the given day in °F

• Average humidity (%) - Avg. humidity at the given day in %

• Average dewpoint (°F) - Avg. dewpoint at the given day in °F

• Average barometer (in) - Avg. barometer reading at the given day. Barometers predict the weather by detecting changes in the air pressure

• Average windspeed (mph) - Avg. windspeed at the given day

• Average gust speed (mph) -  Avg. gust speed at the given date It is a sudden, brief increase in speed of the wind, usually less than 20 seconds

• Average direction (°degree) - Avg. direction of the wind in degree

• Rainfall for month (in) - Rainfall predicted for  the month

• Rainfall for year (in) - Rainfall predicted for the year

• Maximum rain per minute - Max. rain per minute

• Maximum temperature (°F) - Max. temperature predicted for the given day

• Minimum temperature (°F) -Min. temperature predicted for the given day

• Maximum humidity (%) - Max. humidity predicted for the given day

• Minimum humidity (%) - Min. humidity predicted for the given day

• Maximum pressure - Max. pressure predicted for the given day

• Minimum pressure - Min. pressure predicted for the given day

• Maximum wind speed (mph) - Max. wind speed predicted in mph

• Maximum gust speed (mph) - Max. gust speed predicted in mph

• Maximum heat index (°F) - Max. heat index

• Diff pressure - Diff presupressure predicted

### Importing necessary libraries :

We will import the required libraries such as pandas, numpy. Pandas will help in data analysis and manipulation, while numpy works with the arrays use for scientific computing. It provides a high-performance multidimensional array object, and tools.

In [44]:
import numpy as np                              #importing numpy as np
import pandas as pd                             #importing pandas as pd

### To read csv dataset :

We will import our data into the jupyter noterbook and use pandas to read csv file and to store it in a dataframe in order to clean and analyse as follows:

In [45]:
df = pd.read_excel ('weather_dataset_stage1.xls', skiprows=28)   #to read the csv file
pd.pandas.set_option('display.max_columns', None)                #to print the all columns
df.head(5)

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,Maximum temperature (°F,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0','0.0','40.0','34.0','4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
1,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0','0.0','52.0','37.0','4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
2,2022-01-03','25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0','0.0','41.0','6.0','8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
3,2022-01-04','9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0','0.0','19.0','-0.0','7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'
4,2022-01-05','23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0','0.0','30.0','15.0','5.0','13.0','30.233','29.568','38.0','53.0','32.0','2022-01-05','01','0.6649999999999991'

### Basic Exploration of the dataset :
We will perform basic exploration of the dataset to understand data given.

In [46]:
#To know the size of database using shape function
df.shape

(3903, 23)

In [47]:
# Exploring first 10 rows of the dataset using head function
df.head(5)

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,Maximum temperature (°F,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0','0.0','40.0','34.0','4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
1,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0','0.0','52.0','37.0','4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
2,2022-01-03','25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0','0.0','41.0','6.0','8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
3,2022-01-04','9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0','0.0','19.0','-0.0','7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'
4,2022-01-05','23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0','0.0','30.0','15.0','5.0','13.0','30.233','29.568','38.0','53.0','32.0','2022-01-05','01','0.6649999999999991'

In [48]:
# Exploring last 10 rows of dataset using tail function.
df.tail(5)

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,Maximum temperature (°F,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
3898,2022-07-25','62.8','60.0','48.1','29.7','2.5','4.0','242.0','0.33','4.47','0.0','69.2','55.1','90.0','36.0','29.781','29.645','8.1','17.3','77.5','2022-07-25','07','0.13599999999999923'
3899,2022-07-26','60.6','68.0','48.9','29.8','1.7','2.9','357.0','0.33','4.47','0.0','71.9','50.5','90.0','40.0','29.93','29.745','11.5','15.0','77.5','2022-07-26','07','0.18499999999999872'
3900,2022-07-27','61.7','64.0','47.4','29.9','2.2','4.0','66.0','0.33','4.47','0.0','77.3','43.6','96.0','35.0','29.941','29.781','13.8','18.4','78.2','2022-07-27','07','0.16000000000000014'
3901,2022-07-28','60.5','61.0','45.3','29.7','4.0','6.2','248.0','0.35','4.49','0.0','75.6','46.0','94.0','35.0','29.792','29.675','17.3','26.5','77.6','2022-07-28','07','0.11700000000000088';
3902,2022-07-28','60.5','61.0','45.3','29.7','4.0','6.2','248.0','0.35','4.49','0.0','75.6','46.0','94.0','35.0','29.792','29.675','17.3','26.5','77.6','2022-07-28','07','0.11700000000000088';

In [49]:
#To check for basic information of the dataset such as null elements and datatypes of column, memory usage by data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3903 entries, 0 to 3902
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      3903 non-null   object
 1    Temperature              3903 non-null   object
 2    Average humidity (%      3903 non-null   object
 3    Average dewpoint (°F     3903 non-null   object
 4    Average barometer (in    3903 non-null   object
 5    Average windspeed (mph   3903 non-null   object
 6    Average gustspeed (mph   3903 non-null   object
 7    Average direction (°deg  3903 non-null   object
 8    Rainfall for month (in   3903 non-null   object
 9   Rainfall for year (in     3903 non-null   object
 10   Maximum rain per minute  3903 non-null   object
 11   Maximum temperature (°F  3903 non-null   object
 12   Minimum temperature (°F  3903 non-null   object
 13   Maximum humidity (%      3903 non-null   object
 14   Minimum humidity (%      3903 non-null   object
 15   Maximum pressure         3903 non-null   object
 16   Minimum pressure         3903 non-null   object
 17   Maximum windspeed (mph   3903 non-null   object
 18   Maximum gust speed (mph  3903 non-null   object
 19   Maximum heat index (°F   3903 non-null   object
 20  Date1                     3903 non-null   object
 21   Month                    3903 non-null   object
 22   diff_pressure            3903 non-null   object
dtypes: object(23)
memory usage: 701.4+ KB

In [50]:
#to check which column have missing values using isna()
df.isna().sum()

Date                        0
 Temperature                0
 Average humidity (%        0
 Average dewpoint (°F       0
 Average barometer (in      0
 Average windspeed (mph     0
 Average gustspeed (mph     0
 Average direction (°deg    0
 Rainfall for month (in     0
Rainfall for year (in       0
 Maximum rain per minute    0
 Maximum temperature (°F    0
 Minimum temperature (°F    0
 Maximum humidity (%        0
 Minimum humidity (%        0
 Maximum pressure           0
 Minimum pressure           0
 Maximum windspeed (mph     0
 Maximum gust speed (mph    0
 Maximum heat index (°F     0
Date1                       0
 Month                      0
 diff_pressure              0
dtype: int64

Using info(),isna() function we get to know following information about the given dataset:

• There are total 3902 entries i.e. there are 8618 rows and 23 columns.

• All column's datatypes are reading as object type which is incorrect.

• There are no null values present in dataset.

## Pre-processing and Data Cleaning using Python :

As a Data Analyst, data cleaning is inevitable process. It is the process of handling or removing incorrect, corrupted, incorrectly formatted, duplicate, or incomplete data within a dataset. It is a part of the data preparation process. Data cleansing allows for accurate, defensible data that generates reliable visualizations, models, and business decisions.

In our given raw dataset, there are some duplicates, trailed whitespaces, missing data and incorrect data. We will further process data cleaning part.

In [51]:
#to strip unnecessary char from both ends
df = df.apply(lambda x:x.str.strip("';'"))

In [52]:
df.tail()

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,Maximum temperature (°F,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
3898,2022-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,0.0,69.2,55.1,90.0,36.0,29.781,29.645,8.1,17.3,77.5,2022-07-25,07,0.13599999999999923
3899,2022-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,0.0,71.9,50.5,90.0,40.0,29.93,29.745,11.5,15.0,77.5,2022-07-26,07,0.18499999999999872
3900,2022-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,0.0,77.3,43.6,96.0,35.0,29.941,29.781,13.8,18.4,78.2,2022-07-27,07,0.16000000000000014
3901,2022-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,2022-07-28,07,0.11700000000000088
3902,2022-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,2022-07-28,07,0.11700000000000088

In [53]:
df.head()

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,Maximum temperature (°F,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,2022-01-01,01,0.16600000000000037
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,2022-01-02,01,0.4009999999999998
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,0.0,41.0,6.0,8.0,35.0,30.232,29.26,25.3,38.0,41.0,2022-01-03,01,0.9719999999999978
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,2022-01-04,01,0.33899999999999864
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,2022-01-05,01,0.6649999999999991

In [54]:
#to strip whitespaces if present from both end
df = df.apply(lambda x:x.str.strip())            
df.head()

,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,Maximum rain per minute,Maximum temperature (°F,Minimum temperature (°F,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,2022-01-01,01,0.16600000000000037
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,2022-01-02,01,0.4009999999999998
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,0.0,41.0,6.0,8.0,35.0,30.232,29.26,25.3,38.0,41.0,2022-01-03,01,0.9719999999999978
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,2022-01-04,01,0.33899999999999864
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,2022-01-05,01,0.6649999999999991

### Exploring  and handling columns :

In [55]:
#to explore columns present
df.columns

Index(['Date', ' Temperature', ' Average humidity (%', ' Average dewpoint (°F',
       ' Average barometer (in', ' Average windspeed (mph',
       ' Average gustspeed (mph', ' Average direction (°deg',
       ' Rainfall for month (in', 'Rainfall for year (in',
       ' Maximum rain per minute', ' Maximum temperature (°F',
       ' Minimum temperature (°F', ' Maximum humidity (%',
       ' Minimum humidity (%', ' Maximum pressure', ' Minimum pressure',
       ' Maximum windspeed (mph', ' Maximum gust speed (mph',
       ' Maximum heat index (°F', 'Date1', ' Month', ' diff_pressure'],
      dtype='object')

We will rename column names using .rename() for better readiablity.

In [56]:
#to rename columns
df.rename(columns={
  'Date': 'Date',
  ' Temperature': 'Average_temperature',
  ' Average humidity (%': 'Average_humidity',
  ' Average dewpoint (°F': 'Average_dewpoint',
  ' Average barometer (in': 'Average_barometer',
  ' Average windspeed (mph': 'Average_windspeed',
  ' Average gustspeed (mph': 'Average_gust_speed',
  ' Average direction (°deg': 'Average_direction_degree',
  ' Rainfall for month (in': 'Rainfall_for_month',
  'Rainfall for year (in': 'Rainfall_for_year',
  ' Maximum rain per minute': 'Maximum_rain_per_minute',
  ' Maximum temperature (°F': 'Maximum_temperature',
  ' Minimum temperature (°F': 'Minimum_temperature',
  ' Maximum humidity (%': 'Maximum_humidity',
  ' Minimum humidity (%': 'Minimum_humidity',
  ' Maximum pressure': 'Maximum_pressure',
  ' Minimum pressure': 'Minimum_pressure',
  ' Maximum windspeed (mph': 'Maximum_windspeed',
  ' Maximum gust speed (mph': 'Maximum_gust_speed',
  ' Maximum heat index (°F': 'Maximum_heat_index',
  'Date1': 'Date1',
  ' Month': 'Month',
  ' diff_pressure': 'Diff_pressure'
}, inplace=True)

In [57]:
#to check new column names
df.columns

Index(['Date', 'Average_temperature', 'Average_humidity', 'Average_dewpoint',
       'Average_barometer', 'Average_windspeed', 'Average_gust_speed',
       'Average_direction_degree', 'Rainfall_for_month', 'Rainfall_for_year',
       'Maximum_rain_per_minute', 'Maximum_temperature', 'Minimum_temperature',
       'Maximum_humidity', 'Minimum_humidity', 'Maximum_pressure',
       'Minimum_pressure', 'Maximum_windspeed', 'Maximum_gust_speed',
       'Maximum_heat_index', 'Date1', 'Month', 'Diff_pressure'],
      dtype='object')

In [58]:
df.head()

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Date1,Month,Diff_pressure
0,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,0.0,40.0,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,2022-01-01,01,0.16600000000000037
1,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,0.0,52.0,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,2022-01-02,01,0.4009999999999998
2,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,0.0,41.0,6.0,8.0,35.0,30.232,29.26,25.3,38.0,41.0,2022-01-03,01,0.9719999999999978
3,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,0.0,19.0,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,2022-01-04,01,0.33899999999999864
4,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,0.0,30.0,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,2022-01-05,01,0.6649999999999991

### Fixing Data Types of Columns :

We will change the data types of Date column to Datetime and other columns as Float.

In [59]:
#changing Date column to datetime
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d', errors='coerce')
df['Date'].dtype

dtype('<M8[ns]')

In [60]:
df.info()          #to check column info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3903 entries, 0 to 3902
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      3901 non-null   datetime64[ns]
 1   Average_temperature       3903 non-null   object
 2   Average_humidity          3903 non-null   object
 3   Average_dewpoint          3903 non-null   object
 4   Average_barometer         3903 non-null   object
 5   Average_windspeed         3903 non-null   object
 6   Average_gust_speed        3903 non-null   object
 7   Average_direction_degree  3903 non-null   object
 8   Rainfall_for_month        3903 non-null   object
 9   Rainfall_for_year         3903 non-null   object
 10  Maximum_rain_per_minute   3903 non-null   object
 11  Maximum_temperature       3903 non-null   object
 12  Minimum_temperature       3903 non-null   object
 13  Maximum_humidity          3903 non-null   object
 14  Minimum_humidity          3903 non-null   object
 15  Maximum_pressure          3903 non-null   object
 16  Minimum_pressure          3903 non-null   object
 17  Maximum_windspeed         3903 non-null   object
 18  Maximum_gust_speed        3903 non-null   object
 19  Maximum_heat_index        3903 non-null   object
 20  Date1                     3903 non-null   object
 21  Month                     3903 non-null   object
 22  Diff_pressure             3903 non-null   object
dtypes: datetime64[ns](1), object(22)
memory usage: 701.4+ KB

We can see Date1 and Month are unnecessary columns we can drop them.

In [61]:
#to drop columns
df = df.drop(columns=['Date1', 'Month'])

Now, we will change the data types of remaining columns excluding Date column.

In [62]:
exclude_col = ['Date']

In [63]:
# to  get a list of all column names, except for the excluded column
cols = [col
        for col in df.columns
        if col not in exclude_col]

In [64]:
cols

['Average_temperature',
 'Average_humidity',
 'Average_dewpoint',
 'Average_barometer',
 'Average_windspeed',
 'Average_gust_speed',
 'Average_direction_degree',
 'Rainfall_for_month',
 'Rainfall_for_year',
 'Maximum_rain_per_minute',
 'Maximum_temperature',
 'Minimum_temperature',
 'Maximum_humidity',
 'Minimum_humidity',
 'Maximum_pressure',
 'Minimum_pressure',
 'Maximum_windspeed',
 'Maximum_gust_speed',
 'Maximum_heat_index',
 'Diff_pressure']

In [65]:
df[cols] = df[cols].apply(lambda x: x.astype(float))             #changing datatypes to float

In [66]:
df.info()           #successfully changed

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3903 entries, 0 to 3902
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      3901 non-null   datetime64[ns]
 1   Average_temperature       3903 non-null   float64
 2   Average_humidity          3903 non-null   float64
 3   Average_dewpoint          3903 non-null   float64
 4   Average_barometer         3903 non-null   float64
 5   Average_windspeed         3903 non-null   float64
 6   Average_gust_speed        3903 non-null   float64
 7   Average_direction_degree  3903 non-null   float64
 8   Rainfall_for_month        3903 non-null   float64
 9   Rainfall_for_year         3903 non-null   float64
 10  Maximum_rain_per_minute   3903 non-null   float64
 11  Maximum_temperature       3903 non-null   float64
 12  Minimum_temperature       3903 non-null   float64
 13  Maximum_humidity          3903 non-null   float64
 14  Minimum_humidity          3903 non-null   float64
 15  Maximum_pressure          3903 non-null   float64
 16  Minimum_pressure          3903 non-null   float64
 17  Maximum_windspeed         3903 non-null   float64
 18  Maximum_gust_speed        3903 non-null   float64
 19  Maximum_heat_index        3903 non-null   float64
 20  Diff_pressure             3903 non-null   float64
dtypes: datetime64[ns](1), float64(20)
memory usage: 640.5 KB

### To fix incorrect year in Date column :
This is most challenging task in this dataset. In our raw dataset, Date column is corrupted. We can see only 2022 year throughout the year. But the given data is day wise weather attributes from 2022 to July 2033 (predicted
data). We have to change year from 2022 to 2033.

First we will assign target_date as '2022-01-01'. Whenever we will find 2022-01-01, we will increment a year.
Replace for all rows with a new year,till we encounter '2022-01-01' and continue till the end.

In [86]:
target_date = '2022-01-01'                         
target_date = pd.to_datetime(target_date)
index = df.index[df['Date'] == target_date].tolist()
year = 2021
max_year = 2033

for i in range(index[0], df.shape[0]):
    if df.at[i, 'Date'] == target_date:
        year += 1
        if year > max_year:
            break
    df.at[i, 'Date'] = df.at[i, 'Date'].replace(year=year)

In [87]:
df.tail(50)

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Diff_pressure
3852,2033-06-09,46.7,49.0,27.5,29.7,7.9,13.3,254.0,0.15,3.55,0.0,55.0,38.7,72.0,31.0,29.868,29.525,21.9,34.5,55.0,0.3430
3853,2033-06-10,51.9,40.0,27.6,30.0,6.7,10.5,239.0,0.15,3.55,0.0,64.4,44.8,52.0,24.0,30.017,29.859,18.4,33.4,64.4,0.1580
3854,2033-06-11,55.0,43.0,30.2,30.1,2.4,4.4,129.0,0.15,3.55,0.0,71.3,32.6,80.0,18.0,30.137,30.005,12.7,17.3,76.0,0.1320
3855,2033-06-12,61.5,39.0,31.7,30.0,2.9,5.0,75.0,0.15,3.55,0.0,80.7,36.0,80.0,12.0,30.137,29.826,13.8,20.7,79.0,0.3110
3856,2033-06-13,61.2,45.0,37.6,29.7,3.8,6.2,255.0,0.20,3.60,0.0,80.2,41.1,77.0,16.0,29.838,29.545,19.6,32.2,78.6,0.2930
3857,2033-06-14,65.7,26.0,25.6,29.5,8.0,11.7,226.0,0.20,3.60,0.0,78.7,49.3,55.0,9.0,29.592,29.446,28.8,40.3,77.3,0.1460
3858,2033-06-15,59.9,30.0,25.3,29.7,2.0,3.6,297.0,0.20,3.60,0.0,82.4,39.2,54.0,10.0,29.796,29.598,11.5,19.6,79.9,0.1980
3859,2033-06-16,65.3,28.0,27.2,29.5,6.2,9.6,245.0,0.20,3.60,0.0,81.5,40.8,63.0,14.0,29.688,29.397,19.6,28.8,79.3,0.2910
3860,2033-06-17,64.4,28.0,26.1,29.4,6.2,9.5,251.0,0.20,3.60,0.0,82.0,42.6,58.0,9.0,29.517,29.404,19.6,26.5,79.6,0.1130
3861,2033-06-18,53.2,56.0,36.6,29.7,3.7,6.5,72.0,0.27,3.67,0.0,62.3,44.4,91.0,35.0,29.873,29.518,12.7,19.6,62.3,0.3550
3862,2033-06-19,48.8,81.0,43.1,29.9,2.2,3.8,48.0,0.52,3.92,0.0,56.3,41.6,94.0,63.0,29.898,29.804,20.7,31.1,56.3,0.0940
3863,2033-06-20,56.3,49.0,31.2,29.8,3.8,6.3,252.0,0.53,3.93,0.0,77.6,32.2,96.0,13.0,29.941,29.752,18.4,24.2,76.7,0.1890
3864,2033-06-21,58.9,48.0,38.0,29.7,3.4,5.4,252.0,0.55,3.95,0.0,71.5,47.7,78.0,24.0,29.753,29.608,13.8,29.9,77.0,0.1450
3865,2033-06-22,57.1,62.0,43.2,29.8,2.5,4.3,16.0,0.55,3.95,0.0,70.2,39.8,93.0,38.0,29.913,29.734,13.8,18.4,77.5,0.1790
3866,2033-06-23,58.8,64.0,45.1,29.8,2.4,3.9,18.0,0.63,4.03,0.0,75.6,42.0,92.0,31.0,29.930,29.733,17.3,21.9,77.4,0.1970
3867,2033-06-24,59.7,63.0,44.1,29.7,2.8,4.5,313.0,0.73,4.13,0.0,81.4,40.7,96.0,22.0,29.787,29.641,15.0,23.0,79.9,0.1460
3868,2033-06-25,62.6,50.0,38.9,29.6,3.9,6.2,242.0,0.73,4.13,0.0,81.8,40.7,95.0,16.0,29.731,29.599,24.2,33.4,79.6,0.1320
3869,2033-06-26,57.8,66.0,46.0,29.7,3.0,4.8,13.0,0.74,4.14,0.0,72.5,44.0,87.0,42.0,29.809,29.660,17.3,27.6,77.4,0.1490
3870,2033-06-27,64.5,36.0,35.1,29.6,5.6,8.8,238.0,0.74,4.14,0.0,78.5,47.4,78.0,17.0,29.762,29.406,21.9,33.4,77.8,0.3560
3871,2033-06-28,66.1,34.0,36.1,29.3,5.5,8.8,234.0,0.74,4.14,0.0,76.3,49.6,58.0,23.0,29.406,29.222,19.6,33.4,77.4,0.1840
3872,2033-06-29,65.3,38.0,34.7,29.3,4.0,6.5,243.0,0.74,4.14,0.0,86.2,42.7,81.0,13.0,29.351,29.214,19.6,31.1,82.8,0.1370
3873,2033-06-30,58.6,34.0,28.3,29.4,10.6,16.0,237.0,0.74,4.14,0.0,66.3,49.7,56.0,16.0,29.678,29.254,27.6,39.1,66.3,0.4240
3874,2033-07-01,59.9,33.0,26.7,29.7,4.2,7.1,217.0,0.00,4.14,0.0,76.5,37.7,67.0,11.0,29.774,29.626,19.6,29.9,76.2,0.1480
3875,2033-07-02,64.2,34.0,29.5,29.7,3.9,6.3,233.0,0.00,4.14,0.0,83.4,38.9,73.0,10.0,29.790,29.661,16.1,26.5,80.7,0.1290
3876,2033-07-03,67.4,37.0,37.7,29.7,3.6,6.1,348.0,0.00,4.14,0.0,84.5,48.5,62.0,14.0,29.826,29.681,23.0,33.4,81.5,0.1450
3877,2033-07-04,62.2,55.0,44.0,29.7,3.9,6.1,306.0,0.03,4.17,0.0,85.6,49.6,81.0,19.0,29.800,29.662,25.3,39.1,82.5,0.1380
3878,2033-07-05,61.0,57.0,42.7,29.8,2.1,3.5,290.0,0.08,4.22,0.0,82.5,40.6,93.0,21.0,29.819,29.744,15.0,21.9,80.3,0.0750
3879,2033-07-06,65.1,45.0,38.5,29.7,2.7,4.6,206.0,0.08,4.22,0.0,84.9,42.9,88.0,12.0,29.771,29.658,16.1,23.0,81.8,0.1130
3880,2033-07-07,68.6,29.0,28.4,29.6,4.9,7.6,222.0,0.08,4.22,0.0,86.3,44.2,68.0,9.0,29.676,29.454,20.7,32.2,82.9,0.2220
3881,2033-07-08,65.5,19.0,17.3,29.5,4.4,7.0,246.0,0.08,4.22,0.0,84.7,39.1,44.0,7.0,29.629,29.502,18.4,28.8,81.7,0.1270
3882,2033-07-09,64.1,33.0,30.8,29.7,3.1,5.1,40.0,0.08,4.22,0.0,84.8,40.4,69.0,8.0,29.740,29.609,16.1,26.5,81.7,0.1310
3883,2033-07-10,68.7,32.0,24.3,29.8,3.6,6.0,253.0,0.08,4.22,0.0,90.7,43.1,84.0,5.0,29.821,29.713,20.7,27.6,86.6,0.1080
3884,2033-07-11,67.0,29.0,32.8,29.8,2.6,4.6,71.0,0.08,4.22,0.0,83.9,44.8,43.0,18.0,29.902,29.751,13.8,18.4,81.2,0.1510
3885,2033-07-12,68.3,34.0,35.6,29.7,5.1,8.1,237.0,0.08,4.22,0.0,84.0,46.0,69.0,11.0,29.778,29.572,19.6,33.4,81.1,0.2060
3886,2033-07-13,73.4,29.0,38.3,29.5,7.4,11.6,235.0,0.08,4.22,0.0,85.5,64.4,45.0,17.0,29.575,29.374,26.5,41.4,82.3,0.2022
3887,2033-07-14,62.4,56.0,45.2,29.5,3.2,5.2,2.0,0.10,4.24,0.0,78.2,53.5,88.0,27.0,29.700,29.434,17.3,26.5,78.3,0.2660
3888,2033-07-15,62.3,65.0,49.6,29.7,3.3,6.0,67.0,0.10,4.24,0.0,73.3,47.7,91.0,29.0,29.799,29.651,13.8,19.6,77.5,0.1480
3889,2033-07-16,65.7,63.0,52.8,29.7,2.3,4.6,93.0,0.10,4.24,0.0,65.7,65.7,63.0,63.0,29.746,29.746,2.3,4.6,65.7,0.0000
3890,2033-07-17,65.7,63.0,52.8,29.7,2.3,4.6,79.0,0.10,4.24,0.0,65.7,65.7,63.0,63.0,29.746,29.746,2.3,4.6,65.7,0.0000
3891,2033-07-18,76.3,24.0,35.5,29.6,7.3,11.4,236.0,0.10,4.24,0.0,87.2,61.2,63.0,10.0,29.746,29.537,19.6,31.1,83.6,0.2090
3892,2033-07-19,66.6,38.0,39.0,29.6,3.7,5.7,226.0,0.12,4.26,0.0,80.9,50.2,64.0,16.0,29.679,29.602,18.4,25.3,79.1,0.0770
3893,2033-07-20,70.1,35.0,37.4,29.6,4.9,8.0,293.0,0.12,4.26,0.0,85.4,54.4,74.0,9.0,29.650,29.505,17.3,27.6,82.3,0.1450
3894,2033-07-21,65.3,60.0,49.8,29.6,3.7,6.3,38.0,0.12,4.26,0.0,79.2,46.8,88.0,31.0,29.710,29.568,13.8,19.6,79.5,0.1420
3895,2033-07-22,65.4,52.0,42.7,29.6,4.2,6.7,230.0,0.12,4.26,0.0,85.9,46.9,93.0,14.0,29.707,29.583,16.1,25.3,82.6,0.1240
3896,2033-07-23,67.1,48.0,45.2,29.6,5.3,8.6,228.0,0.23,4.37,0.0,81.1,54.8,87.0,26.0,29.668,29.571,19.6,24.2,79.7,0.0970
3897,2033-07-24,64.1,62.0,49.8,29.6,3.6,5.8,240.0,0.24,4.38,0.0,74.9,55.3,86.0,35.0,29.686,29.577,15.0,25.3,77.4,0.1090
3898,2033-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,0.0,69.2,55.1,90.0,36.0,29.781,29.645,8.1,17.3,77.5,0.1360
3899,2033-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,0.0,71.9,50.5,90.0,40.0,29.930,29.745,11.5,15.0,77.5,0.1850
3900,2033-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,0.0,77.3,43.6,96.0,35.0,29.941,29.781,13.8,18.4,78.2,0.1600
3901,2033-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,0.1170

In [80]:
random_date = '2024-02-29'
rows = df.loc[df['Date'] == random_date]                        #to check for any uncommon values present 
rows

Empty DataFrame
Columns: [Date, Average_temperature, Average_humidity, Average_dewpoint, Average_barometer, Average_windspeed, Average_gust_speed, Average_direction_degree, Rainfall_for_month, Rainfall_for_year, Maximum_rain_per_minute, Maximum_temperature, Minimum_temperature, Maximum_humidity, Minimum_humidity, Maximum_pressure, Minimum_pressure, Maximum_windspeed, Maximum_gust_speed, Maximum_heat_index, Diff_pressure]
Index: []

In [88]:
df['Date']           #exploring date column

0      2022-01-01
1      2022-01-02
2      2022-01-03
3      2022-01-04
4      2022-01-05
          ...
3897   2033-07-24
3898   2033-07-25
3899   2033-07-26
3900   2033-07-27
3901   2033-07-28
Name: Date, Length: 3902, dtype: datetime64[ns]

### Handling Duplicates :

In [89]:
df[df.duplicated()] #to show duplicate records

Empty DataFrame
Columns: [Date, Average_temperature, Average_humidity, Average_dewpoint, Average_barometer, Average_windspeed, Average_gust_speed, Average_direction_degree, Rainfall_for_month, Rainfall_for_year, Maximum_rain_per_minute, Maximum_temperature, Minimum_temperature, Maximum_humidity, Minimum_humidity, Maximum_pressure, Minimum_pressure, Maximum_windspeed, Maximum_gust_speed, Maximum_heat_index, Diff_pressure]
Index: []

In [90]:
#dropping all duplicates from df
df.drop_duplicates(inplace=True)
df.tail()

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Diff_pressure
3897,2033-07-24,64.1,62.0,49.8,29.6,3.6,5.8,240.0,0.24,4.38,0.0,74.9,55.3,86.0,35.0,29.686,29.577,15.0,25.3,77.4,0.109
3898,2033-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,0.0,69.2,55.1,90.0,36.0,29.781,29.645,8.1,17.3,77.5,0.136
3899,2033-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,0.0,71.9,50.5,90.0,40.0,29.930,29.745,11.5,15.0,77.5,0.185
3900,2033-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,0.0,77.3,43.6,96.0,35.0,29.941,29.781,13.8,18.4,78.2,0.160
3901,2033-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,0.0,75.6,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,0.117

Here we have ssuccessfully dropped the duplicates!

Now we will check for the leap year data

In [92]:
df[(df['Date'].dt.month == 2) & (df['Date'].dt.day == 29)]

Empty DataFrame
Columns: [Date, Average_temperature, Average_humidity, Average_dewpoint, Average_barometer, Average_windspeed, Average_gust_speed, Average_direction_degree, Rainfall_for_month, Rainfall_for_year, Maximum_rain_per_minute, Maximum_temperature, Minimum_temperature, Maximum_humidity, Minimum_humidity, Maximum_pressure, Minimum_pressure, Maximum_windspeed, Maximum_gust_speed, Maximum_heat_index, Diff_pressure]
Index: []

We will change format of date column to date-only.

In [93]:
df['Date'].dtype
df['Date'] = df['Date'].dt.date #to convert the datetime column to a date-only format

### Dealing with null values :

In [32]:
df.isnull().sum()            #to check for null values

Date                        2
Average_temperature         0
Average_humidity            0
Average_dewpoint            0
Average_barometer           0
Average_windspeed           0
Average_gust_speed          0
Average_direction_degree    0
Rainfall_for_month          0
Rainfall_for_year           0
Maximum_rain_per_minute     0
Maximum_temperature         0
Minimum_temperature         0
Maximum_humidity            0
Minimum_humidity            0
Maximum_pressure            0
Minimum_pressure            0
Maximum_windspeed           0
Maximum_gust_speed          0
Maximum_heat_index          0
Diff_pressure               0
dtype: int64

In [33]:
df[df.isna().any(axis=1)]            #exploring for null values

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Diff_pressure
2366,NaT,38.1,36.0,12.3,29.8,11.5,17.0,77.0,0.16,0.36,0.0,45.9,27.9,73.0,22.0,30.023,29.702,29.9,39.1,45.9,0.321
3751,NaT,37.6,31.0,8.7,29.8,8.0,11.6,236.0,0.48,0.49,0.0,48.1,26.1,57.0,20.0,29.972,29.647,19.6,31.1,48.1,0.325

In [34]:
df.iloc[[2365,2366,2367,3750,3751,3752]]     #exploring more about null values

,Date,Average_temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gust_speed,Average_direction_degree,Rainfall_for_month,Rainfall_for_year,Maximum_rain_per_minute,Maximum_temperature,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Diff_pressure
2365,2029-02-28,42.2,25.0,7.1,29.9,8.7,13.2,58.0,0.16,0.36,0.0,53.6,31.5,44.0,11.0,29.942,29.749,25.3,36.8,53.6,0.193
2366,NaT,38.1,36.0,12.3,29.8,11.5,17.0,77.0,0.16,0.36,0.0,45.9,27.9,73.0,22.0,30.023,29.702,29.9,39.1,45.9,0.321
2367,2029-03-01,36.4,30.0,7.6,30.0,7.9,12.5,23.0,0.00,0.21,0.0,47.0,24.5,51.0,22.0,30.125,29.817,24.2,34.5,47.0,0.308
3750,2033-02-28,37.7,30.0,8.3,30.1,11.0,15.9,224.0,0.48,0.49,0.0,47.0,29.5,38.0,21.0,30.194,29.970,24.2,42.6,47.0,0.224
3751,NaT,37.6,31.0,8.7,29.8,8.0,11.6,236.0,0.48,0.49,0.0,48.1,26.1,57.0,20.0,29.972,29.647,19.6,31.1,48.1,0.325
3752,2033-03-01,28.7,66.0,17.8,29.7,4.1,6.5,34.0,0.00,0.49,0.0,38.2,17.1,90.0,36.0,29.903,29.622,16.1,23.0,38.2,0.281

As we can see above, null values are for the date where 29th day was present in the feb for non leap year. We can drop it.

In [35]:
df.dropna(inplace=True)    #dropping rows having NaT values

In [36]:
df[df.isna().any(axis=1)]             #successfully dropped

Empty DataFrame
Columns: [Date, Average_temperature, Average_humidity, Average_dewpoint, Average_barometer, Average_windspeed, Average_gust_speed, Average_direction_degree, Rainfall_for_month, Rainfall_for_year, Maximum_rain_per_minute, Maximum_temperature, Minimum_temperature, Maximum_humidity, Minimum_humidity, Maximum_pressure, Minimum_pressure, Maximum_windspeed, Maximum_gust_speed, Maximum_heat_index, Diff_pressure]
Index: []

We have completed all preprocessing and data cleaning. Final shape of our dataset is:

In [37]:
df.shape

(3900, 21)

## To Export Clean Dataset into csv File :

In [38]:
df.to_csv('weather_datasetcleaned.csv', index=False, encoding='utf-8')

***
## Conclusion :

- We have done all pre-processing using python alone with the help of Pandas and Numpy. 
- Corruped data, duplicates and missed data handled and fixed successfully.